dev_addr: 0.0.0.0:8000
site_name: EvalCSU

repo_url: https://github.com/Jacob953/evalcsu
repo_name: Jacob953/evalcsu

theme:
  name: material
  language: zh
  custom_dir: "overrides/"

  features:
  - navigation.tabs
  - navigation.top
  
  logo: assets/logo.png

  icon:
    repo: fontawesome/brands/github-square

nav:
- 简介:
  - EvalCSU: /evalcsu/
- 评教:
  - 计算机学院: 
    - 计算机科学与技术: evaluation/cse/science.md
    - 大数据: evaluation/cse/bigdata.md
    - 信息安全: evaluation/cse/security.md
    - 物联网: evaluation/cse/iot.md
    - 软件工程: evaluation/cse/software.md
  - 自动化学院:
    - 自动化: evaluation/soa/automation.md
    - 电子工程及其自动化: evaluation/soa/electronic_information.md
    - 智能科学与技术: evaluation/soa/intelligence.md
- 笔记:
  - 计算机学院: 
    - 专业规划: 
      - 概括: faculty/cse/index.md
    - 大数据:
      - 数据库:
        - experiment1: faculty/cse/bigdata/Database/experiment1.md
        - experiment2: faculty/cse/bigdata/Database/experiment2.md
      - Oracle:
        - Experiment:
          - experiment-1: faculty/cse/bigdata/Oracle/Experiment/experiment-1.md
          - experiment-2: faculty/cse/bigdata/Oracle/Experiment/experiment-2.md
          - experiment-3: faculty/cse/bigdata/Oracle/Experiment/experiment-3.md
          - experiment-4: faculty/cse/bigdata/Oracle/Experiment/experiment-4.md
          - experiment-5: faculty/cse/bigdata/Oracle/Experiment/experiment-5.md
        - Note:
          - Advanced: faculty/cse/bigdata/Oracle/Note/Advanced.md
          - Execution_Plan: faculty/cse/bigdata/Oracle/Note/Execution_Plan.md
          - Oracle_Architecture: faculty/cse/bigdata/Oracle/Note/Oracle_Architecture.md
          - Oracle_Schema: faculty/cse/bigdata/Oracle/Note/Oracle_Schema.md
          - PL_SQL1: faculty/cse/bigdata/Oracle/Note/PL_SQL1.md
          - PL_SQL2: faculty/cse/bigdata/Oracle/Note/PL_SQL2.md
        - Oracle: faculty/cse/bigdata/Oracle/README.md
      - R语言:
        - Experiment:
          - experiment-1: faculty/cse/bigdata/R-language/Experiment/experiment-1.md
          - experiment-2: faculty/cse/bigdata/R-language/Experiment/experiment-2.md
        - Note:
          - BasicStructure: faculty/cse/bigdata/R-language/Note/BasicStructure.md
          - DataAnalysis: faculty/cse/bigdata/R-language/Note/DataAnalysis.md
          - dataOp: faculty/cse/bigdata/R-language/Note/dataOp.md
          - Grammar: faculty/cse/bigdata/R-language/Note/Grammar.md
          - ML: faculty/cse/bigdata/R-language/Note/ML.md
          - Plot: faculty/cse/bigdata/R-language/Note/Plot.md
        - R-language: faculty/cse/bigdata/R-language/README.md
      - Web 技术:
        - web-lab-report: faculty/cse/bigdata/Web-technology/web-lab-report.md
    - 信息安全:
      - 网络安全:
        - ARP 嗅探: faculty/cse/security/network-security/arp-spoofing.md
        - BGP 路由劫持: faculty/cse/security/network-security/bgp-route-hijacking.md
        - DNS 服务: faculty/cse/security/network-security/dns-server.md
        - Dos 拒绝服务攻击: faculty/cse/security/network-security/dos.md
        - IPsec: faculty/cse/security/network-security/ipsec.md
        - 邮件中继: faculty/cse/security/network-security/mail-relay.md
        - 一次性口令: faculty/cse/security/network-security/onetime-password.md
        - 远程安全认证: faculty/cse/security/network-security/remote-security-authentication.md
        - 路由协议: faculty/cse/security/network-security/routing-protocol.md
        - 盐值: faculty/cse/security/network-security/salt-value.md
        - SYN-Cookies: faculty/cse/security/network-security/syn-cookies.md
        - TSL / SSL: faculty/cse/security/network-security/tls-ssl.md
      - 软件工程:
        - 小米笔记: faculty/cse/security/software/MiCode-Note.md
  - 自动化学院:
    - 专业规划: 
      - 概括: faculty/soa/index.md
    - 自动化:
      - 数据结构:
        - 图遍历: faculty/soa/automation/datastructure/graph-traval.md
        - 哈夫曼编码: faculty/soa/automation/datastructure/Huffman.md
      - 自动化: faculty/soa/automation/README.md
    - 智能科学与技术:
      - 智能科学与技术: faculty/soa/intelligence/README.md
- 贡献指南: global/zh-simplify/contribution/
- 加入我们: global/join/
# - global:
#   - en:
#     - CONTRIBUTION: global/en/contribution/
#   - EVALUATOR: global/evaluator/
#   - GENERALTIPS: global/GENERALTIPS.md
#   - zh-simplify:
#     - CONTRIBUTION: global/zh-simplify/contribution/
#     - git-helper:
#       - Git_Branch-Manager: global/zh-simplify/git-helper/Git_Branch-Manager.md
#       - Git_Custom: global/zh-simplify/git-helper/Git_Custom.md
#       - Git_Remote-Repository: global/zh-simplify/git-helper/Git_Remote-Repository.md
#       - Git_Self-Inctroduction: global/zh-simplify/git-helper/Git_Self-Inctroduction.md
#       - Git_Tag-Manager: global/zh-simplify/git-helper/Git_Tag-Manager.md
#       - Git_Time-Traveler: global/zh-simplify/git-helper/Git_Time-Traveler.md
#       - git-helper: global/zh-simplify/git-helper/README.md
#     - 菜鸟教程: global/zh-simplify/noobguide/
#     - 菜鸟教程-Git: global/zh-simplify/noobguide-git/
#   - zh-tradition:
#     - CONTRIBUTION: global/zh-tradition/contribution/

